### ISSUE TITLE
Server offline after 15m

### ISSUE THREAD

**Issue by flyworker** [swanchain/python-swan-sdk#51]
Create a hello world task with

https://github.com/flyworker/swan-test/blob/main/hello-world.py

logs:

2024-08-25 18:10:18,208 - INFO - Login Successfully!
2024-08-25 18:10:18,208 - INFO - Using Mainnet
2024-08-25 18:10:18,871 - INFO - Using C1ae.small machine, hardware_id=0 region='global' duration=3600 (seconds)
2024-08-25 18:10:30,501 - INFO - Payment submitted, task_uuid='5f9d2925-bf55-4cb3-b829-20935b011ce1', duration=3600, hardware_id=0. Got tx_hash='0xcea5a5f649fbe3f9bace9abeaf58e58ca7101b3a1fba643f6bd2802be883b065'
2024-08-25 18:10:33,686 - INFO - Payment validation request sent, task_uuid='5f9d2925-bf55-4cb3-b829-20935b011ce1', tx_hash='0xcea5a5f649fbe3f9bace9abeaf58e58ca7101b3a1fba643f6bd2802be883b065'
2024-08-25 18:10:33,686 - INFO - Payment submitted and validated successfully, task_uuid='5f9d2925-bf55-4cb3-b829-20935b011ce1', tx_hash='0xcea5a5f649fbe3f9bace9abeaf58e58ca7101b3a1fba643f6bd2802be883b065'
2024-08-25 18:10:33,686 - INFO - Task created successfully, task_uuid='5f9d2925-bf55-4cb3-b829-20935b011ce1', tx_hash='0xcea5a5f649fbe3f9bace9abeaf58e58ca7101b3a1fba643f6bd2802be883b065', hardware_id=0
{'data': {'computing_providers': [], 'jobs': [], 'task': {'comments': None, 'created_at': 1724623819, 'end_at': 1724627419, 'id': 26912, 'leading_job_id': None, 'name': None, 'refund_amount': None, 'refund_wallet': '0xA41c36BCd65bDbFB62FE93E3b7a28d290E63C1F7', 'source': 'v2', 'start_at': 1724623819, 'start_in': 300, 'status': 'initialized', 'task_detail': {'amount': 0.0, 'bidder_limit': 3, 'created_at': 1724623819, 'dcc_selected_cp_list': None, 'duration': 3600, 'end_at': 1724627419, 'hardware': 'C1ae.small', 'job_result_uri': None, 'job_source_uri': 'https://orchestrator-mainnet-api.swanchain.io/spaces/7609ea78-103c-41b6-9560-9f574f98b5e4', 'price_per_hour': '0.0', 'requirements': {'hardware': 'None', 'hardware_type': 'CPU', 'memory': '2', 'preferred_cp_list': None, 'region': 'global', 'storage': None, 'update_max_lag': None, 'vcpu': '2'}, 'space': {'activeOrder': {'config': {'description': 'CPU only · 2 vCPU · 2 GiB', 'hardware': 'CPU only', 'hardware_id': 0, 'hardware_type': 'CPU', 'memory': 2, 'name': 'C1ae.small', 'price_per_hour': 0.0, 'vcpu': 2}}, 'name': '0', 'uuid': '37f9d927-c029-4e7b-8664-aa13e9947e51'}, 'start_at': 1724623819, 'status': 'paid', 'storage_source': 'swanhub', 'type': 'None', 'updated_at': 1724623819}, 'task_detail_cid': 'https://data.mcs.lagrangedao.org/ipfs/QmczR2DCigKA2vhT3Qxq5kFCe9RDxPW9uTJXgecLAfWzcZ', 'tx_hash': None, 'type': 'None', 'updated_at': 1724623833, 'user_id': 4146, 'uuid': '5f9d2925-bf55-4cb3-b829-20935b011ce1'}}, 'message': "fetch task info for task_uuid='5f9d2925-bf55-4cb3-b829-20935b011ce1' successfully", 'status': 'success'}

fetch the result with after 15m

def test_get_task_infot(setup_swan_orchestrator):
    swan_orchestrator = setup_swan_orchestrator
    task_info = swan_orchestrator.get_deployment_info(task_uuid="5f9d2925-bf55-4cb3-b829-20935b011ce1")
    print(json.dumps(task_info, indent=2))

   
============================= test session starts ==============================
collecting ... collected 1 item

test_get_server_list.py::test_get_task_infot PASSED                      [100%]{
  "data": {
    "computing_providers": [
      {
        "beneficiary": "0xd5731fecF5c19f11CFF4517bed893F3D20Ad6E12",
        "cp_account_address": "0xaE0d78257e7EbAeaE3e75A292F7cdC17A60410Ae",
        "created_at": 1723441451,
        "freeze_online": null,
        "id": 2062,
        "lat": 22.3193,
        "lon": 114.169,
        "multi_address": [
          "/ip4/8.218.145.52/tcp/10078"
        ],
        "name": "863d9E1BE6075",
        "node_id": "0473d08825f5463ed0ebaff25a2b245b9f8c51f21c35a902906863cb76d0762a0e59156381210303e189af9f6a8d81de8d1e1bd5a8db86be69b6fff1ec65a4a5b7",
        "online": 1,
        "owner_address": "0xd5731fecF5c19f11CFF4517bed893F3D20Ad6E12",
        "region": "Kowloon-HK",
        "task_types": "[3]",
        "updated_at": 1724624817,
        "version": "2.0",
        "worker_address": "0xd5731fecF5c19f11CFF4517bed893F3D20Ad6E12"
      },
      {
        "beneficiary": "0x97D2A063A37178451f404cb34CB60Bad2E8F6e10",
        "cp_account_address": "0x1D6C5f3fAD7d010f98AC32a10ce518A242F1Ed4B",
        "created_at": 1723906166,
        "freeze_online": null,
        "id": 2131,
        "lat": 48.884,
        "lon": 2.29217,
        "multi_address": [
          "/ip4/185.98.128.99/tcp/8085"
        ],
        "name": "swancontainer",
        "node_id": "041ef51c442039ed966bf2e3e6dc5880a364ce2432e296c6b4f3565b4561f154974d79991208510a8159852fc54de56b30710b49dccf380bf816acf05c87478dbc",
        "online": 0,
        "owner_address": "0x97D2A063A37178451f404cb34CB60Bad2E8F6e10",
        "region": "\u00cele-de-France-FR",
        "task_types": "[3]",
        "updated_at": 1724624388,
        "version": "2.0",
        "worker_address": "0x97D2A063A37178451f404cb34CB60Bad2E8F6e10"
      },
      {
        "beneficiary": "0x876153501308f5712A393F243657F590Bf886429",
        "cp_account_address": "0x8dc1B11c2386462eCF9b36eF1e1a85489dE7369e",
        "created_at": 1723442081,
        "freeze_online": null,
        "id": 2072,
        "lat": 22.3193,
        "lon": 114.169,
        "multi_address": [
          "/ip4/8.218.145.52/tcp/10088"
        ],
        "name": "20e8cd92",
        "node_id": "04156cc97f67a993180c5bfcb892c96aa23716209b859d83567ec6c9bec641f10df3f21425490fbecf34fad3635cdecf23e1a65ff747f77cb660fa97f63d031e1b",
        "online": 1,
        "owner_address": "0x876153501308f5712A393F243657F590Bf886429",
        "region": "Kowloon-HK",
        "task_types": "[3]",
        "updated_at": 1724624331,
        "version": "2.0",
        "worker_address": "0x876153501308f5712A393F243657F590Bf886429"
      }
    ],
    "jobs": [
      {
        "build_log": "wss://log.1.3242.cn:10078/api/v1/computing/lagrange/spaces/log?space_id=7609ea78-103c-41b6-9560-9f574f98b5e4&type=build",
        "comments": "Running(buildImage). buildImage: no job_real_uri from api. buildImage: updated job_result_uri. buildImage(Submitted).",
        "container_log": "wss://log.1.3242.cn:10078/api/v1/computing/lagrange/spaces/log?space_id=7609ea78-103c-41b6-9560-9f574f98b5e4&type=container",
        "cp_account_address": "0xaE0d78257e7EbAeaE3e75A292F7cdC17A60410Ae",
        "created_at": 1724623840,
        "duration": 3600,
        "ended_at": null,
        "hardware": "C1ae.small",
        "id": 8641,
        "job_real_uri": "https://nkqplps6z6.1.3242.cn",
        "job_result_uri": "https://fb6d9c863374.acl.swanipfs.com/ipfs/QmWbkVUcgoW1hDzTzFHgWN1yEsecZKV6HJScSqRs2eB2BM",
        "job_source_uri": "https://orchestrator-mainnet-api.swanchain.io/spaces/7609ea78-103c-41b6-9560-9f574f98b5e4",
        "name": "Job-32beaf29-43a1-4b9f-99f3-d0676e3d5fb0",
        "node_id": "0473d08825f5463ed0ebaff25a2b245b9f8c51f21c35a902906863cb76d0762a0e59156381210303e189af9f6a8d81de8d1e1bd5a8db86be69b6fff1ec65a4a5b7",
        "start_at": 1724623844,
        "status": "Running",
        "storage_source": "swanhub",
        "task_uuid": "5f9d2925-bf55-4cb3-b829-20935b011ce1",
        "type": null,
        "updated_at": 1724623930,
        "uuid": "32beaf29-43a1-4b9f-99f3-d0676e3d5fb0"
      },
      {
        "build_log": "wss://log.sc.altafser.com:8085/api/v1/computing/lagrange/spaces/log?space_id=7609ea78-103c-41b6-9560-9f574f98b5e4&type=build",
        "comments": null,
        "container_log": "wss://log.sc.altafser.com:8085/api/v1/computing/lagrange/spaces/log?space_id=7609ea78-103c-41b6-9560-9f574f98b5e4&type=container",
        "cp_account_address": "0x1D6C5f3fAD7d010f98AC32a10ce518A242F1Ed4B",
        "created_at": 1724623844,
        "duration": 3600,
        "ended_at": null,
        "hardware": "C1ae.small",
        "id": 8642,
        "job_real_uri": "https://fkpkrt1prf.sc.altafser.com",
        "job_result_uri": null,
        "job_source_uri": "https://orchestrator-mainnet-api.swanchain.io/spaces/7609ea78-103c-41b6-9560-9f574f98b5e4",
        "name": "Job-40323305-3f30-4946-bfbf-0622bbf434f6",
        "node_id": "041ef51c442039ed966bf2e3e6dc5880a364ce2432e296c6b4f3565b4561f154974d79991208510a8159852fc54de56b30710b49dccf380bf816acf05c87478dbc",
        "start_at": 1724623845,
        "status": "Submitted",
        "storage_source": "swanhub",
        "task_uuid": "5f9d2925-bf55-4cb3-b829-20935b011ce1",
        "type": null,
        "updated_at": 1724623845,
        "uuid": "40323305-3f30-4946-bfbf-0622bbf434f6"
      },
      {
        "build_log": "wss://log.1.3242.cn:10088/api/v1/computing/lagrange/spaces/log?space_id=7609ea78-103c-41b6-9560-9f574f98b5e4&type=build",
        "comments": "downloadSource: updated job_result_uri. downloadSource(Submitted).",
        "container_log": "wss://log.1.3242.cn:10088/api/v1/computing/lagrange/spaces/log?space_id=7609ea78-103c-41b6-9560-9f574f98b5e4&type=container",
        "cp_account_address": "0x8dc1B11c2386462eCF9b36eF1e1a85489dE7369e",
        "created_at": 1724623845,
        "duration": 3600,
        "ended_at": null,
        "hardware": "C1ae.small",
        "id": 8643,
        "job_real_uri": "https://f9xuc5ze6v.1.3242.cn",
        "job_result_uri": "https://fb6d9c863374.acl.swanipfs.com/ipfs/QmUG1v46m1w75znM9JCYRWu3qjveqWYYJFkRSpUb5esBEv",
        "job_source_uri": "https://orchestrator-mainnet-api.swanchain.io/spaces/7609ea78-103c-41b6-9560-9f574f98b5e4",
        "name": "Job-448e32a3-535d-4f28-aba4-b7ad347f00a0",
        "node_id": "04156cc97f67a993180c5bfcb892c96aa23716209b859d83567ec6c9bec641f10df3f21425490fbecf34fad3635cdecf23e1a65ff747f77cb660fa97f63d031e1b",
        "start_at": 1724623847,
        "status": "downloadSource",
        "storage_source": "swanhub",
        "task_uuid": "5f9d2925-bf55-4cb3-b829-20935b011ce1",
        "type": null,
        "updated_at": 1724623917,
        "uuid": "448e32a3-535d-4f28-aba4-b7ad347f00a0"
      }
    ],
    "task": {
      "comments": null,
      "created_at": 1724623819,
      "end_at": 1724627419,
      "id": 26912,
      "leading_job_id": "32beaf29-43a1-4b9f-99f3-d0676e3d5fb0",
      "name": null,
      "refund_amount": null,
      "refund_wallet": "0xA41c36BCd65bDbFB62FE93E3b7a28d290E63C1F7",
      "source": "v2",
      "start_at": 1724623819,
      "start_in": 300,
      "status": "completed",
      "task_detail": {
        "amount": 0.0,
        "bidder_limit": 3,
        "created_at": 1724623819,
        "dcc_selected_cp_list": null,
        "duration": 3600,
        "end_at": 1724627419,
        "hardware": "C1ae.small",
        "job_result_uri": null,
        "job_source_uri": "https://orchestrator-mainnet-api.swanchain.io/spaces/7609ea78-103c-41b6-9560-9f574f98b5e4",
        "price_per_hour": "0.0",
        "requirements": {
          "hardware": "None",
          "hardware_type": "CPU",
          "memory": "2",
          "preferred_cp_list": null,
          "region": "global",
          "storage": null,
          "update_max_lag": null,
          "vcpu": "2"
        },
        "space": {
          "activeOrder": {
            "config": {
              "description": "CPU only \u00b7 2 vCPU \u00b7 2 GiB",
              "hardware": "CPU only",
              "hardware_id": 0,
              "hardware_type": "CPU",
              "memory": 2,
              "name": "C1ae.small",
              "price_per_hour": 0.0,
              "vcpu": 2
            }
          },
          "name": "0",
          "uuid": "37f9d927-c029-4e7b-8664-aa13e9947e51"
        },
        "start_at": 1724623819,
        "status": "paid",
        "storage_source": "swanhub",
        "type": "None",
        "updated_at": 1724623819
      },
      "task_detail_cid": "https://data.mcs.lagrangedao.org/ipfs/QmczR2DCigKA2vhT3Qxq5kFCe9RDxPW9uTJXgecLAfWzcZ",
      "tx_hash": null,
      "type": "None",
      "updated_at": 1724623850,
      "user_id": 4146,
      "uuid": "5f9d2925-bf55-4cb3-b829-20935b011ce1"
    }
  },
  "message": "fetch task info for task_uuid='5f9d2925-bf55-4cb3-b829-20935b011ce1' successfully",
  "status": "success"
}

   

It is offline

**Comment by alphaflows** [comment]
Thank you for posting this issue. Computing providers behind `3242.cn` intentionally killed jobs after 15 minutes. A solution has been figured out to avoid this situation.
