### ISSUE TITLE
SDK documentation

### ISSUE THREAD

**Issue by flyworker** [swanchain/python-swan-sdk#53]
# Swan Python SDK Documentation

## Overview

The Swan Python SDK provides an intuitive interface for interacting with the Swan network, enabling developers to manage cloud resources, tasks, and payments with ease. This SDK abstracts the complexities of the underlying API, allowing you to focus on building your applications.

## Table of Contents

1. [Installation](#installation)
2. [Getting Started](#getting-started)
3. [Initialization and Configuration](#initialization-and-configuration)
4. [Task Management](#task-management)
5. [Hardware Management](#hardware-management)
6. [Payment Management](#payment-management)
7. [Asynchronous Operations](#asynchronous-operations)
8. [Error Handling](#error-handling)
9. [Logging and Monitoring](#logging-and-monitoring)
10. [Advanced Usage](#advanced-usage)
11. [Command-Line Interface (CLI)](#command-line-interface-cli)
12. [Contributing](#contributing)
13. [License](#license)

## Installation

Install the Swan Python SDK via pip:

```bash
pip install swan-sdk
```

Alternatively, you can clone the repository and install it directly:

```bash
git clone https://github.com/swanchain/python-swan-sdk.git
cd python-swan-sdk
pip install .
```

## Getting Started

To start using the SDK, import the necessary modules and initialize the client:

```python
from swan_sdk import SwanClient

client = SwanClient(api_key="your_api_key", region="global")
```

### Initialization

You can initialize the SDK with various configuration options:

```python
client = SwanClient(
    api_key="your_api_key",
    region="global",
    url_endpoint="https://api.swan.io/v1"
)
```

### Configuration from Environment Variables

The SDK can be configured using environment variables:

```bash
export SWAN_API_KEY="your_api_key"
export SWAN_REGION="global"
```

Then, in your code:

```python
import os
from swan_sdk import SwanClient

client = SwanClient(
    api_key=os.getenv('SWAN_API_KEY'),
    region=os.getenv('SWAN_REGION', 'global')
)
```

### Configuration from a File

Load configuration from a JSON or YAML file:

```python
client = SwanClient.from_config_file("config.json")
```

### Creating a Task

To create a task on the Swan network:

```python
task = client.create_task(
    wallet_address="0xYourWalletAddress",
    hardware_id=0,
    duration=3600,
    app_repo_image="your_app_image",
    job_source_uri="https://your-repo-uri"
)
print(f"Task created with UUID: {task['uuid']}")
```

### Terminating a Task

To terminate an existing task:

```python
client.terminate_task(task_uuid="your_task_uuid")
print("Task terminated successfully")
```

### Listing Tasks

To list all tasks:

```python
tasks = client.list_tasks()
for task in tasks:
    print(task)
```

### Fetching Hardware Configurations

Retrieve available hardware configurations:

```python
hardware_configs = client.get_hardware_config(available=True)
for config in hardware_configs:
    print(config)
```

### Checking Hardware Availability

Verify if a specific hardware configuration is available in a region:

```python
is_available = client.verify_hardware_region(hardware_name="C1ae.small", region="North Carolina-US")
print(f"Hardware available: {is_available}")
```

### Estimating Payment

Estimate the cost for a task:

```python
estimated_price = client.estimate_payment(hardware_id=0, duration=3600)
print(f"Estimated price: {estimated_price} SWAN")
```

### Submitting Payment

Submit a payment for a task:

```python
tx_hash = client.submit_payment(
    task_uuid="your_task_uuid",
    private_key="your_private_key",
    hardware_id=0,
    duration=3600
)
print(f"Payment submitted with transaction hash: {tx_hash}")
```

### Validating Payment

Validate a payment on the Swan backend:

```python
validation = client.validate_payment(tx_hash="your_tx_hash", task_uuid="your_task_uuid")
print("Payment validated successfully")
```

## Asynchronous Operations

The SDK supports asynchronous operations for non-blocking calls:

```python
import asyncio
from swan_sdk.async_client import AsyncSwanClient

async def main():
    client = AsyncSwanClient(api_key="your_api_key")
    task = await client.create_task(wallet_address="0xYourWalletAddress", hardware_id=0, duration=3600)
    print(task)

asyncio.run(main())
```

## Error Handling

The SDK provides robust error handling with custom exceptions:

```python
from swan_sdk.exceptions import SwanAPIException

try:
    client.create_task(...)
except SwanAPIException as e:
    print(f"An error occurred: {e}")
```

### Custom Exceptions

- `SwanAPIException`: General API errors.
- `SwanAuthenticationException`: Authentication-related errors.
- `SwanTaskException`: Errors related to task management.
- `SwanPaymentException`: Errors related to payments.

### Configurable Logging

Enable logging for better insight into SDK operations:

```python
import logging

logging.basicConfig(level=logging.INFO)
client = SwanClient(api_key="your_api_key", logger=logging.getLogger("swan_sdk"))
```

### Integrating with Cloud Logging

You can integrate the SDK's logging with cloud services like AWS CloudWatch or Google Cloud Logging for centralized monitoring.

### Using Profiles

Use profiles for managing different environments:

```python
client = SwanClient(profile_name="production")
```

### Context Managers for Resource Handling

Automatically manage resources using context managers:

```python
with client.create_task(...) as task:
    print(task.status)
```

## Command-Line Interface (CLI)

The SDK provides a CLI for quick operations:

```bash
swan tasks create --hardware-id 1 --duration 3600
```

### CLI Usage Examples

- **Create a Task**:
  ```bash
  swan tasks create --hardware-id 1 --duration 3600 --wallet-address 0xYourWalletAddress
  ```

- **List Tasks**:
  ```bash
  swan tasks list
  ```

- **Terminate a Task**:
  ```bash
  swan tasks terminate --task-uuid your_task_uuid
  ```

## Contributing

We welcome contributions to improve the Swan Python SDK. Please follow the guidelines in our [CONTRIBUTING.md](https://github.com/swanchain/python-swan-sdk/blob/main/CONTRIBUTING.md) file.

## License

The Swan Python SDK is open-source software licensed under the MIT License. See the [LICENSE](https://github.com/swanchain/python-swan-sdk/blob/main/LICENSE) file for more details.

**Comment by Oyase-shinobi** [comment]
Hello @flyworker 
I would love to engage in your team
